version: "3.8"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DEV_PWD}
      POSTGRES_USER: ${DEV_USER}
      POSTGRES_DB: ${DEV_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  sasnaka-backend:
    build: .
    container_name: sasnaka-backend
    image: sasnaka-backend
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/app
